controller_list:
  - name: fake_r_arm_controller
    joints:
      - r_shoulder_base_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_wrist_roll_joint
  - name: fake_l_arm_controller
    joints:
      - l_shoulder_base_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_wrist_roll_joint
  - name: fake_r_hand_index_controller
    joints:
      - r_index_joint
  - name: fake_r_hand_middle_controller
    joints:
      - r_middle_joint
  - name: fake_r_hand_ring_controller
    joints:
      - r_ring_joint
  - name: fake_r_hand_pinky_controller
    joints:
      - r_pinky_joint
  - name: fake_r_hand_thumb_controller
    joints:
      - r_thumb_joint
  - name: fake_l_hand_index_controller
    joints:
      - l_index_joint
  - name: fake_l_hand_middle_controller
    joints:
      - l_middle_joint
  - name: fake_l_hand_ring_controller
    joints:
      - l_ring_joint
  - name: fake_l_hand_pinky_controller
    joints:
      - l_pinky_joint
  - name: fake_l_hand_thumb_controller
    joints:
      - l_thumb_joint
  - name: fake_r_hand_controller
    joints:
      - r_index_joint
      - r_middle_joint
      - r_pinky_joint
      - r_ring_joint
      - r_thumb_joint
  - name: fake_l_hand_controller
    joints:
      - l_index_joint
      - l_middle_joint
      - l_pinky_joint
      - l_ring_joint
      - l_thumb_joint